### PR TITLE
closes #29

### LINKED ISSUE #29: Bug with Home Directory on different OS's
When Running the `CD` Command on an OS other than Linux it gives the wrong home directory as seen here 
``` c++
string determine_home(){

	struct passwd *pw;
        char *user = NULL;
	pw = getpwuid(geteuid());  
        user = pw->pw_name;
	string home  = "/home/" ; // wrong home directory for Windows and OSX
        home.append(user);
	return home ;
```

### PR DESCRIPTION
**Pull request by Jsostmann**
Fixes `cd` with no arguments error
fixes issue #29 with buggy home directory name on MacOS

### CODE REVIEW

**Comment by Jsostmann** [comment]
Fixed #30 #

**Comment by Jsostmann** [comment]
Closes #29

**Review by Monal5031 — COMMENTED** [review]
Please remove the binary test file

**Review by Monal5031 — CHANGES_REQUESTED** [review]
.

**Comment by Jsostmann** [comment]
@Monal5031 Got it! 🥳

**Review by Jsostmann — COMMENTED** [review]
Deleted Test

**Review by Monal5031 — APPROVED** [review]

**Comment by Monal5031** [comment]
Thank you @Jsostmann for the PR. 🎉

**Comment by Jsostmann** [comment]
@Monal5031 No Problem! Thank you for making this awesome Interpreter!

**Pull request merged**
